# Generated by Django 6.0.4 on 2026-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='color',
            new_name='primary_color',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='font',
        ),
        migrations.AddField(
            model_name='cv',
            name='font_family',
            field=models.CharField(choices=[('DM Sans', 'DM Sans'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Playfair Display', 'Playfair Display'), ('Raleway', 'Raleway')], default='DM Sans', max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cv_photos/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='secondary_color',
            field=models.CharField(default='#e63946', max_length=7),
        ),
    ]
