# Generated by Django 6.0.4 on 2026-05-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_color_cv_primary_color_remove_cv_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small (9pt)'), ('medium', 'Medium (10pt)'), ('large', 'Large (11pt)')], default='medium', max_length=10),
        ),
    ]
