# Generated by Django 6.0.4 on 2026-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_field_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='field_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
